spring:
  datasource:
    username: anhvt
    password: Club2003@

  mail:
    username: clubhubfpt@gmail.com
    password: "kwku usrt eeld uhju"

jwt:
  signerKey: "066f37bf2e51e827ed91c4ad68a3fcfd684c11f52e8ae1f22801bed7c788e1e3"

payos:
  client-id: "5301efbb-b43e-43f5-96fe-2833b57cedfb"
  api-key: "caec2c2d-3871-4763-8ff4-640947354555"
  checksum-key: "612d045d9a61205789f3b47e1b996374829793ea0569bc34b8f86314ba35c13b"